image: docker:20.10.16
variables:
  DOCKER_TLS_CERTDIR: '/certs'
services:
  - docker:20.10.16-dind

stages:
  - build
  - deploy

before_script:
  - apk update -qy && apk add --no-cache curl unzip bash
  - apk add --no-cache python3 && python3 -m ensurepip &&  rm -r /usr/lib/python*/ensurepip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && rm -r /root/.cache
  - pip3 install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 339126146861.dkr.ecr.ap-southeast-1.amazonaws.com

build:
  stage: build
  script:
    - VERSION=$CI_COMMIT_TAG
    - |-
      if [[ "$CI_COMMIT_TAG" == *"-dev"* ]]; then
        docker build -t 339126146861.dkr.ecr.ap-southeast-1.amazonaws.com/reviewty/livestream-scheduler-api:$VERSION .
      else 
        docker build -t 339126146861.dkr.ecr.ap-southeast-1.amazonaws.com/reviewty/livestream-scheduler-api:$VERSION .
      fi
    - docker push 339126146861.dkr.ecr.ap-southeast-1.amazonaws.com/reviewty/livestream-scheduler-api:$VERSION
  only:
    - tags

deploy-dev:
  stage: deploy
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -

    # - |-
    #     if [[ "$CI_COMMIT_TAG" == *"-dev"* ]]; then
    #       CMD="env VERSION=$CI_COMMIT_TAG bash /home/limpi/livestream-api/run.sh"
    #       echo $CMD
    #       ssh -o StrictHostKeyChecking=no -p 2225 limpi@14.248.83.194 $CMD
    #     else
    #       - echo "Nothing to do! Adding a suffix '-dev' to the tag for deploying on the test environment"
    #     fi
    - CMD="env VERSION=$CI_COMMIT_TAG bash /home/limpi/livestream-api/run.sh"
    - echo $CMD
    - ssh -o StrictHostKeyChecking=no -p 2225 limpi@14.248.83.194 $CMD

  only:
    - tags
