import { registerEnumType } from 'type-graphql';

export enum AuthErrorCode {
  OTP_NOT_VALID = 'OTP_NOT_VALID',
  REFERRAL_CODE_INVALID = 'REFERRAL_CODE_INVALID',
  INVALID_REFERRAL_CODE = 'INVALID_REFERRAL_CODE',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  ACCOUNT_ALREADY_IN_USE = 'ACCOUNT_ALREADY_IN_USE',
  FACEBOOK_ALREADY_IN_USE = 'FACEBOOK_ALREADY_IN_USE',
  FACEBOOK_NOT_EXISTS = 'FACEBOOK_NOT_EXISTS',
  APPLE_ALREADY_IN_USE = 'APPLE_ALREADY_IN_USE',
  APPLE_NOT_EXISTS = 'APPLE_NOT_EXISTS',
  ACCOUNT_IS_BLOCKED = 'ACCOUNT_IS_BLOCKED',
  UNAUTHORIZED = 'UNAUTHORIZED',
}

registerEnumType(AuthErrorCode, {
  name: 'AuthErrorCode',
});
