export const LOADER_TYPES = {
  UserQuizAnswerLoader: Symbol.for('UserQuizAnswerLoader'),
  UserQuizLoader: Symbol.for('UserQuizLoader'),
  QuizAnswerLoader: Symbol.for('QuizAnswerLoader'),
  QuizQuestionLoader: Symbol.for('QuizQuestionLoader'),
  QuizLoader: Symbol.for('QuizLoader'),
  ChildContentByCourseContentIdLoader: Symbol.for('ChildContentByCourseContentIdLoader'),
  CourseContentLoader: Symbol.for('CourseContentLoader'),
  S3FileLoader: Symbol.for('S3FileLoader'),
  UserLoader: Symbol.for('UserLoader'),
  ResourceLoader: Symbol.for('ResourceLoader'),
  CourseLoader: Symbol.for('CourseLoader'),
  NewsLoader: Symbol.for('NewsLoader'),
  CourseAttachFileByCourseContentIdLoader: Symbol.for(
    'CourseAttachFileByCourseContentIdLoader',
  ),
  CourseContentByCourseIdLoader: Symbol.for('CourseContentByCourseIdLoader'),
  CourseReviewByCourseIdLoader: Symbol.for('CourseReviewByCourseIdLoader'),
  CourseReactByCourseIdLoader: Symbol.for('CourseReactByCourseIdLoader'),
  CourseViewershipByCourseIdLoader: Symbol.for(
    'CourseViewershipByCourseIdLoader',
  ),
  CourseReviewCountLoader: Symbol.for('CourseReviewCountLoader'),
  CourseReactCountLoader: Symbol.for('CourseReactCountLoader'),
  CourseViewershipCountLoader: Symbol.for('CourseViewershipCountLoader'),
  AverageRatingByCourseIdLoader: Symbol.for('AverageRatingByCourseIdLoader'),
  QuizQuestionByQuizIdLoader: Symbol.for('QuizQuestionByQuizIdLoader'),
  QuizAnswerByQuestionIdLoader: Symbol.for('QuizAnswerByQuestionIdLoader'),
  QuizByCourseContentIdLoader: Symbol.for('QuizByCourseContentIdLoader'),
};
